# Generated by Django 4.2.7 on 2026-08-17 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_bookmark_follow_mention_share_tag_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='bookmark',
            index=models.Index(fields=['user', 'post'], name='bookmarks_user_id_c9f490_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['post', 'parent'], name='comments_post_id_b0a8a6_idx'),
        ),
        migrations.AddIndex(
            model_name='follow',
            index=models.Index(fields=['following'], name='follows_followi_dcb467_idx'),
        ),
        migrations.AddIndex(
            model_name='like',
            index=models.Index(fields=['post', 'user'], name='likes_post_id_063a9e_idx'),
        ),
    ]
