# Generated by Django 4.2.7 on 2026-08-17 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_email_verified_alter_user_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('member', 'Member'), ('trainer', 'Trainer'), ('receptionist', 'Receptionist'), ('admin', 'Admin')], db_index=True, default='member', max_length=20),
        ),
    ]
